# user-db-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: user-db-secrets
  namespace: innowise
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cm9vdA==
  POSTGRES_DB: dXNlcl9zZXJ2aWNlX2Ri