apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: innowise
data:
  SERVER_PORT: "8082"
  SPRING_LIQUIBASE_ENABLED: "true"
  SPRING_LIQUIBASE_CHANGE_LOG: "classpath:db/changelog/db.changelog-master.yaml"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "none"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://order-db:5432/order_service_db"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  ORDER_USER_SERVICE_URL: "http://user-service:8080/api/users"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  SPRING_KAFKA_TOPICS_ORDERS: "orders-topic"
  SPRING_KAFKA_TOPICS_PAYMENTS: "payments-topic"
  SPRING_KAFKA_CONSUMER_GROUP_ID: "order-group"
  SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: "org.apache.kafka.common.serialization.StringSerializer"
  SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: "org.springframework.kafka.support.serializer.JsonSerializer"
  SPRING_KAFKA_PRODUCER_PROPERTIES_SPRING_JSON_ADD_TYPE_HEADERS: "false"
  SPRING_KAFKA_PRODUCER_PROPERTIES_ENABLE_IDEMPOTENCE: "true"
  SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER: "org.apache.kafka.common.serialization.StringDeserializer"
  SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER: "org.springframework.kafka.support.serializer.JsonDeserializer"
  SPRING_KAFKA_CONSUMER_ISOLATION_LEVEL: "read_committed"
  SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_TRUSTED_PACKAGES: "by.osinovi.*"
  SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_VALUE_DEFAULT_TYPE: "by.osinovi.orderservice.dto.message.PaymentMessage"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"