apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: innowise
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=
  SPRING_DATASOURCE_PASSWORD: cm9vdA==
  JWT_SECRET: TUlJQ0lqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FnOEFNSUlDQ2dLQ0FnRQ==