apiVersion: v1
kind: Secret
metadata:
  name: order-db-secrets
  namespace: innowise
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cm9vdA==
  POSTGRES_DB: b3JkZXJfc2VydmljZV9kYg==