apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
  namespace: innowise
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  MONGO_INITDB_ROOT_PASSWORD: cm9vdA==
  MONGO_INITDB_DATABASE: cGF5bWVudF9zZXJ2aWNlX2Ri